<?php

/**
 * @file
 * Contains simple_password_reveal.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function simple_password_reveal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_password_reveal module.
    case 'help.page.simple_password_reveal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds a toggle for showing/hidding password fields.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function simple_password_reveal_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Set passwords to hidden by default.
  $is_checked = \Drupal::config('simple_password_reveal.settings')->get('concealed_default');

  if ($form_id == 'user_login_form') {
    $form['#attached']['library'][] = 'simple_password_reveal/default';

    $form['password_grouping'] = [
      '#type' => 'fieldgroup',
    ];

    $form['password_grouping']['pass'] = $form['pass'];
    unset($form['pass']);

    $form['password_grouping']['simple_password_reveal_checkbox'] = [
      '#type' => 'checkbox',
      '#title' => t('Secure password from plain text view.'),
      '#default_value' => $is_checked,
    ];
  }

  if ($form_id == 'user_form') {
    $form['#attached']['library'][] = 'simple_password_reveal/default';

    $form['account']['password_grouping'] = [
      '#type' => 'fieldgroup',
      '#weight' => -100,
    ];

    $form['account']['password_grouping']['current_pass'] = $form['account']['current_pass'];
    unset($form['account']['current_pass']);

    $form['account']['password_grouping']['simple_password_reveal_checkbox'] = [
      '#type' => 'checkbox',
      '#title' => t('Secure password from plain text view.'),
      '#default_value' => $is_checked,
    ];
  }
}
